name: "Publish Gradle Project"
on: [ push, pull_request ]

jobs:
  publish:
    name: "Publishing"
    if: ${{ !contains(github.event.head_commit.message, '[Publish Skip]') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: "Setup JDK 11"
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: "Cache Gradle"
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: "Cache Maven"
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: "Publish Gradle Package"
        run: |
          chmod +x ./gradlew
          ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}